version: '3.9'

services:
  zookeeper1:
    container_name: zookeeper1
    hostname: zookeeper1
    build:
      context: ./zookeeper
      args:
        ZOOKEEPER_VERSION: "3.7.0"
    environment:
      ZOOKEEPER_ID: "1"
    volumes:
      - zookeeper1-data:/opt/app/data
      - zookeeper1-logs:/opt/app/logs
  zookeeper2:
    container_name: zookeeper2
    hostname: zookeeper2
    build:
      context: ./zookeeper
      args:
        ZOOKEEPER_VERSION: "3.7.0"
    environment:
      ZOOKEEPER_ID: "2"
    volumes:
      - zookeeper2-data:/opt/app/data
      - zookeeper2-logs:/opt/app/logs
  zookeeper3:
    container_name: zookeeper3
    hostname: zookeeper3
    build:
      context: ./zookeeper
      args:
        ZOOKEEPER_VERSION: "3.7.0"
    environment:
      ZOOKEEPER_ID: "3"
    volumes:
      - zookeeper3-data:/opt/app/data
      - zookeeper3-logs:/opt/app/logs
  kafka1:
    container_name: kafka1
    hostname: kafka1
    build:
      context: ./kafka
      args:
        KAFKA_VERSION: "2.8.0"
    environment:
      ZOOKEEPER_HOSTS: "zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
      BROKER_ID: "1"
    volumes:
      - kafka1-data:/opt/app/data
      - kafka1-logs:/opt/app/logs
  kafka2:
    container_name: kafka2
    hostname: kafka2
    build:
      context: ./kafka
      args:
        KAFKA_VERSION: "2.8.0"
    environment:
      ZOOKEEPER_HOSTS: "zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
      BROKER_ID: "2"
    volumes:
      - kafka2-data:/opt/app/data
      - kafka2-logs:/opt/app/logs
  kafka3:
    container_name: kafka3
    hostname: kafka3
    build:
      context: ./kafka
      args:
        KAFKA_VERSION: "2.8.0"
    environment:
      ZOOKEEPER_HOSTS: "zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
      BROKER_ID: "3"
    volumes:
      - kafka3-data:/opt/app/data
      - kafka3-logs:/opt/app/logs

volumes:
  zookeeper1-data:
  zookeeper2-data:
  zookeeper3-data:
  zookeeper1-logs:
  zookeeper2-logs:
  zookeeper3-logs:
  kafka1-data:
  kafka2-data:
  kafka3-data:
  kafka1-logs:
  kafka2-logs:
  kafka3-logs: