version: '3.9'

services:
  zookeeper0:
    container_name: zookeeper0
    hostname: zookeeper0
    build:
      context: ./zookeeper
      args:
        ZOOKEEPER_VERSION: "3.7.0"
    volumes:
      - ${PWD}/zookeeper/files/zoo.cfg:/opt/app/conf/zoo.cfg:rw
      - ${PWD}/zookeeper/files/log4j.properties:/opt/app/conf/log4j.properties:ro
  zookeeper1:
    container_name: zookeeper1
    hostname: zookeeper1
    build:
      context: ./zookeeper
      args:
        ZOOKEEPER_VERSION: "3.7.0"
    volumes:
      - ${PWD}/zookeeper/files/zoo.cfg:/opt/app/conf/zoo.cfg:rw
      - ${PWD}/zookeeper/files/log4j.properties:/opt/app/conf/log4j.properties:ro
  zookeeper2:
    container_name: zookeeper2
    hostname: zookeeper2
    build:
      context: ./zookeeper
      args:
        ZOOKEEPER_VERSION: "3.7.0"
    volumes:
      - ${PWD}/zookeeper/files/zoo.cfg:/opt/app/conf/zoo.cfg:rw
      - ${PWD}/zookeeper/files/log4j.properties:/opt/app/conf/log4j.properties:ro