version: '3.9'

services:
  zookeeper1:
    container_name: zookeeper1
    hostname: zookeeper1
    build:
      context: ./zookeeper
      args:
        ZOOKEEPER_VERSION: "3.7.0"
    environment:
      ZOOKEEPER_ID: "1"
  zookeeper2:
    container_name: zookeeper2
    hostname: zookeeper2
    build:
      context: ./zookeeper
      args:
        ZOOKEEPER_VERSION: "3.7.0"
    environment:
      ZOOKEEPER_ID: "2"
  zookeeper3:
    container_name: zookeeper3
    hostname: zookeeper3
    build:
      context: ./zookeeper
      args:
        ZOOKEEPER_VERSION: "3.7.0"
    environment:
      ZOOKEEPER_ID: "3"